# this is sqlite config
[list]
    [list.default]
        driver_name = "sqlite"
        data_source_name = "gorm.db"
        max_open_conn = 20
        max_idle_conn = 10
        max_conn_life_time = 100